#!/usr/bin/env bash

# if nix is not installed, install it

if ! command -v nix &> /dev/null
then
   curl -L https://nixos.org/nix/install | sh
fi

# execute nix run in a login shell so we know the path will contain nix

bash -lc "nix --refresh --extra-experimental-features 'nix-command flakes' run github:sheeldotme/nairobi/main"
