#!/usr/bin/env bash

# if nix is not installed, install it

if ! command -v nix &> /dev/null
then
   curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tag/v0.11.0 | sh -s -- install
fi

# execute nix run in a login shell so we know the path will contain nix

bash -lc "nix --refresh run github:sheeldotme/nairobi/main"
